'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SurveyMonsterService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType", [Namespace]:="http://schemas.datacontract.org/2004/07/SurveyWCF"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BoolValueField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StringValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BoolValue() As Boolean
            Get
                Return Me.BoolValueField
            End Get
            Set
                If (Me.BoolValueField.Equals(value) <> true) Then
                    Me.BoolValueField = value
                    Me.RaisePropertyChanged("BoolValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StringValue() As String
            Get
                Return Me.StringValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StringValueField, value) <> true) Then
                    Me.StringValueField = value
                    Me.RaisePropertyChanged("StringValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Survey", [Namespace]:="http://schemas.datacontract.org/2004/07/SurveyWCF.SurveyWCF"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Survey
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CreatedByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateCreatedField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EndDateField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsActiveField As System.Nullable(Of Boolean)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastModifiedField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastModifiedByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QuestionsField() As SurveyMonsterService.Question
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StartDateField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SurveyTitleField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TranscriptsField() As SurveyMonsterService.Transcript
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CreatedBy() As String
            Get
                Return Me.CreatedByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CreatedByField, value) <> true) Then
                    Me.CreatedByField = value
                    Me.RaisePropertyChanged("CreatedBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateCreated() As Date
            Get
                Return Me.DateCreatedField
            End Get
            Set
                If (Me.DateCreatedField.Equals(value) <> true) Then
                    Me.DateCreatedField = value
                    Me.RaisePropertyChanged("DateCreated")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EndDate() As System.Nullable(Of Date)
            Get
                Return Me.EndDateField
            End Get
            Set
                If (Me.EndDateField.Equals(value) <> true) Then
                    Me.EndDateField = value
                    Me.RaisePropertyChanged("EndDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsActive() As System.Nullable(Of Boolean)
            Get
                Return Me.IsActiveField
            End Get
            Set
                If (Me.IsActiveField.Equals(value) <> true) Then
                    Me.IsActiveField = value
                    Me.RaisePropertyChanged("IsActive")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LastModified() As System.Nullable(Of Date)
            Get
                Return Me.LastModifiedField
            End Get
            Set
                If (Me.LastModifiedField.Equals(value) <> true) Then
                    Me.LastModifiedField = value
                    Me.RaisePropertyChanged("LastModified")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LastModifiedBy() As String
            Get
                Return Me.LastModifiedByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastModifiedByField, value) <> true) Then
                    Me.LastModifiedByField = value
                    Me.RaisePropertyChanged("LastModifiedBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Questions() As SurveyMonsterService.Question()
            Get
                Return Me.QuestionsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.QuestionsField, value) <> true) Then
                    Me.QuestionsField = value
                    Me.RaisePropertyChanged("Questions")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StartDate() As System.Nullable(Of Date)
            Get
                Return Me.StartDateField
            End Get
            Set
                If (Me.StartDateField.Equals(value) <> true) Then
                    Me.StartDateField = value
                    Me.RaisePropertyChanged("StartDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SurveyTitle() As String
            Get
                Return Me.SurveyTitleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SurveyTitleField, value) <> true) Then
                    Me.SurveyTitleField = value
                    Me.RaisePropertyChanged("SurveyTitle")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Transcripts() As SurveyMonsterService.Transcript()
            Get
                Return Me.TranscriptsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TranscriptsField, value) <> true) Then
                    Me.TranscriptsField = value
                    Me.RaisePropertyChanged("Transcripts")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Question", [Namespace]:="http://schemas.datacontract.org/2004/07/SurveyWCF.SurveyWCF"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Question
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CreatedByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateCreatedField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastModifiedField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastModifiedByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PossibleAnswersField() As SurveyMonsterService.PossibleAnswer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QuestionTextField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SurveyField As SurveyMonsterService.Survey
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SurveyIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TranscriptItemsField() As SurveyMonsterService.TranscriptItem
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TranscriptsField() As SurveyMonsterService.Transcript
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CreatedBy() As String
            Get
                Return Me.CreatedByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CreatedByField, value) <> true) Then
                    Me.CreatedByField = value
                    Me.RaisePropertyChanged("CreatedBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateCreated() As Date
            Get
                Return Me.DateCreatedField
            End Get
            Set
                If (Me.DateCreatedField.Equals(value) <> true) Then
                    Me.DateCreatedField = value
                    Me.RaisePropertyChanged("DateCreated")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LastModified() As System.Nullable(Of Date)
            Get
                Return Me.LastModifiedField
            End Get
            Set
                If (Me.LastModifiedField.Equals(value) <> true) Then
                    Me.LastModifiedField = value
                    Me.RaisePropertyChanged("LastModified")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LastModifiedBy() As String
            Get
                Return Me.LastModifiedByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastModifiedByField, value) <> true) Then
                    Me.LastModifiedByField = value
                    Me.RaisePropertyChanged("LastModifiedBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PossibleAnswers() As SurveyMonsterService.PossibleAnswer()
            Get
                Return Me.PossibleAnswersField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PossibleAnswersField, value) <> true) Then
                    Me.PossibleAnswersField = value
                    Me.RaisePropertyChanged("PossibleAnswers")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property QuestionText() As String
            Get
                Return Me.QuestionTextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.QuestionTextField, value) <> true) Then
                    Me.QuestionTextField = value
                    Me.RaisePropertyChanged("QuestionText")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Survey() As SurveyMonsterService.Survey
            Get
                Return Me.SurveyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SurveyField, value) <> true) Then
                    Me.SurveyField = value
                    Me.RaisePropertyChanged("Survey")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SurveyId() As Integer
            Get
                Return Me.SurveyIdField
            End Get
            Set
                If (Me.SurveyIdField.Equals(value) <> true) Then
                    Me.SurveyIdField = value
                    Me.RaisePropertyChanged("SurveyId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TranscriptItems() As SurveyMonsterService.TranscriptItem()
            Get
                Return Me.TranscriptItemsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TranscriptItemsField, value) <> true) Then
                    Me.TranscriptItemsField = value
                    Me.RaisePropertyChanged("TranscriptItems")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Transcripts() As SurveyMonsterService.Transcript()
            Get
                Return Me.TranscriptsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TranscriptsField, value) <> true) Then
                    Me.TranscriptsField = value
                    Me.RaisePropertyChanged("Transcripts")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Transcript", [Namespace]:="http://schemas.datacontract.org/2004/07/SurveyWCF.SurveyWCF"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Transcript
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CreatedByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateCreatedField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsCorrectField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastModifiedField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ModifiedByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QuestionIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RespondentIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ScoreField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SurveyField As SurveyMonsterService.Survey
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SurveyIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TranscriptItemsField() As SurveyMonsterService.TranscriptItem
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CreatedBy() As String
            Get
                Return Me.CreatedByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CreatedByField, value) <> true) Then
                    Me.CreatedByField = value
                    Me.RaisePropertyChanged("CreatedBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateCreated() As Date
            Get
                Return Me.DateCreatedField
            End Get
            Set
                If (Me.DateCreatedField.Equals(value) <> true) Then
                    Me.DateCreatedField = value
                    Me.RaisePropertyChanged("DateCreated")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsCorrect() As Boolean
            Get
                Return Me.IsCorrectField
            End Get
            Set
                If (Me.IsCorrectField.Equals(value) <> true) Then
                    Me.IsCorrectField = value
                    Me.RaisePropertyChanged("IsCorrect")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LastModified() As System.Nullable(Of Date)
            Get
                Return Me.LastModifiedField
            End Get
            Set
                If (Me.LastModifiedField.Equals(value) <> true) Then
                    Me.LastModifiedField = value
                    Me.RaisePropertyChanged("LastModified")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ModifiedBy() As String
            Get
                Return Me.ModifiedByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ModifiedByField, value) <> true) Then
                    Me.ModifiedByField = value
                    Me.RaisePropertyChanged("ModifiedBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property QuestionId() As Integer
            Get
                Return Me.QuestionIdField
            End Get
            Set
                If (Me.QuestionIdField.Equals(value) <> true) Then
                    Me.QuestionIdField = value
                    Me.RaisePropertyChanged("QuestionId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RespondentId() As String
            Get
                Return Me.RespondentIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RespondentIdField, value) <> true) Then
                    Me.RespondentIdField = value
                    Me.RaisePropertyChanged("RespondentId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Score() As System.Nullable(Of Decimal)
            Get
                Return Me.ScoreField
            End Get
            Set
                If (Me.ScoreField.Equals(value) <> true) Then
                    Me.ScoreField = value
                    Me.RaisePropertyChanged("Score")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Survey() As SurveyMonsterService.Survey
            Get
                Return Me.SurveyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SurveyField, value) <> true) Then
                    Me.SurveyField = value
                    Me.RaisePropertyChanged("Survey")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SurveyId() As Integer
            Get
                Return Me.SurveyIdField
            End Get
            Set
                If (Me.SurveyIdField.Equals(value) <> true) Then
                    Me.SurveyIdField = value
                    Me.RaisePropertyChanged("SurveyId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TranscriptItems() As SurveyMonsterService.TranscriptItem()
            Get
                Return Me.TranscriptItemsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TranscriptItemsField, value) <> true) Then
                    Me.TranscriptItemsField = value
                    Me.RaisePropertyChanged("TranscriptItems")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="PossibleAnswer", [Namespace]:="http://schemas.datacontract.org/2004/07/SurveyWCF.SurveyWCF"),  _
     System.SerializableAttribute()>  _
    Partial Public Class PossibleAnswer
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CreatedByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateCreatedField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsCorrectAnswerField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastModifiedField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ModifiedByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PossibleAnswerTextField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QuestionField As SurveyMonsterService.Question
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QuestionIdField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CreatedBy() As String
            Get
                Return Me.CreatedByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CreatedByField, value) <> true) Then
                    Me.CreatedByField = value
                    Me.RaisePropertyChanged("CreatedBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateCreated() As Date
            Get
                Return Me.DateCreatedField
            End Get
            Set
                If (Me.DateCreatedField.Equals(value) <> true) Then
                    Me.DateCreatedField = value
                    Me.RaisePropertyChanged("DateCreated")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsCorrectAnswer() As Boolean
            Get
                Return Me.IsCorrectAnswerField
            End Get
            Set
                If (Me.IsCorrectAnswerField.Equals(value) <> true) Then
                    Me.IsCorrectAnswerField = value
                    Me.RaisePropertyChanged("IsCorrectAnswer")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LastModified() As System.Nullable(Of Date)
            Get
                Return Me.LastModifiedField
            End Get
            Set
                If (Me.LastModifiedField.Equals(value) <> true) Then
                    Me.LastModifiedField = value
                    Me.RaisePropertyChanged("LastModified")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ModifiedBy() As String
            Get
                Return Me.ModifiedByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ModifiedByField, value) <> true) Then
                    Me.ModifiedByField = value
                    Me.RaisePropertyChanged("ModifiedBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PossibleAnswerText() As String
            Get
                Return Me.PossibleAnswerTextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PossibleAnswerTextField, value) <> true) Then
                    Me.PossibleAnswerTextField = value
                    Me.RaisePropertyChanged("PossibleAnswerText")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Question() As SurveyMonsterService.Question
            Get
                Return Me.QuestionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.QuestionField, value) <> true) Then
                    Me.QuestionField = value
                    Me.RaisePropertyChanged("Question")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property QuestionId() As Integer
            Get
                Return Me.QuestionIdField
            End Get
            Set
                If (Me.QuestionIdField.Equals(value) <> true) Then
                    Me.QuestionIdField = value
                    Me.RaisePropertyChanged("QuestionId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TranscriptItem", [Namespace]:="http://schemas.datacontract.org/2004/07/SurveyWCF.SurveyWCF"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TranscriptItem
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CreatedByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateCreatedField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsCorrectField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastModifiedField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ModifiedByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QuestionField As SurveyMonsterService.Question
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QuestionIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SelectedAnswerIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TranscriptField As SurveyMonsterService.Transcript
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TranscriptIdField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CreatedBy() As String
            Get
                Return Me.CreatedByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CreatedByField, value) <> true) Then
                    Me.CreatedByField = value
                    Me.RaisePropertyChanged("CreatedBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateCreated() As Date
            Get
                Return Me.DateCreatedField
            End Get
            Set
                If (Me.DateCreatedField.Equals(value) <> true) Then
                    Me.DateCreatedField = value
                    Me.RaisePropertyChanged("DateCreated")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsCorrect() As Boolean
            Get
                Return Me.IsCorrectField
            End Get
            Set
                If (Me.IsCorrectField.Equals(value) <> true) Then
                    Me.IsCorrectField = value
                    Me.RaisePropertyChanged("IsCorrect")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LastModified() As System.Nullable(Of Date)
            Get
                Return Me.LastModifiedField
            End Get
            Set
                If (Me.LastModifiedField.Equals(value) <> true) Then
                    Me.LastModifiedField = value
                    Me.RaisePropertyChanged("LastModified")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ModifiedBy() As String
            Get
                Return Me.ModifiedByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ModifiedByField, value) <> true) Then
                    Me.ModifiedByField = value
                    Me.RaisePropertyChanged("ModifiedBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Question() As SurveyMonsterService.Question
            Get
                Return Me.QuestionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.QuestionField, value) <> true) Then
                    Me.QuestionField = value
                    Me.RaisePropertyChanged("Question")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property QuestionId() As Integer
            Get
                Return Me.QuestionIdField
            End Get
            Set
                If (Me.QuestionIdField.Equals(value) <> true) Then
                    Me.QuestionIdField = value
                    Me.RaisePropertyChanged("QuestionId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SelectedAnswerId() As Integer
            Get
                Return Me.SelectedAnswerIdField
            End Get
            Set
                If (Me.SelectedAnswerIdField.Equals(value) <> true) Then
                    Me.SelectedAnswerIdField = value
                    Me.RaisePropertyChanged("SelectedAnswerId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Transcript() As SurveyMonsterService.Transcript
            Get
                Return Me.TranscriptField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TranscriptField, value) <> true) Then
                    Me.TranscriptField = value
                    Me.RaisePropertyChanged("Transcript")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TranscriptId() As Integer
            Get
                Return Me.TranscriptIdField
            End Get
            Set
                If (Me.TranscriptIdField.Equals(value) <> true) Then
                    Me.TranscriptIdField = value
                    Me.RaisePropertyChanged("TranscriptId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SurveyMonsterService.ISurveyWCFService")>  _
    Public Interface ISurveyWCFService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/GetData", ReplyAction:="http://tempuri.org/ISurveyWCFService/GetDataResponse")>  _
        Function GetData(ByVal value As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/GetData", ReplyAction:="http://tempuri.org/ISurveyWCFService/GetDataResponse")>  _
        Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/ISurveyWCFService/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContract(ByVal composite As SurveyMonsterService.CompositeType) As SurveyMonsterService.CompositeType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/ISurveyWCFService/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContractAsync(ByVal composite As SurveyMonsterService.CompositeType) As System.Threading.Tasks.Task(Of SurveyMonsterService.CompositeType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/GetAllActiveSurveys", ReplyAction:="http://tempuri.org/ISurveyWCFService/GetAllActiveSurveysResponse")>  _
        Function GetAllActiveSurveys() As SurveyMonsterService.Survey()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/GetAllActiveSurveys", ReplyAction:="http://tempuri.org/ISurveyWCFService/GetAllActiveSurveysResponse")>  _
        Function GetAllActiveSurveysAsync() As System.Threading.Tasks.Task(Of SurveyMonsterService.Survey())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/AddQuestion", ReplyAction:="http://tempuri.org/ISurveyWCFService/AddQuestionResponse")>  _
        Function AddQuestion(ByVal SurveyId As Integer, ByVal Q As SurveyMonsterService.Question) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/AddQuestion", ReplyAction:="http://tempuri.org/ISurveyWCFService/AddQuestionResponse")>  _
        Function AddQuestionAsync(ByVal SurveyId As Integer, ByVal Q As SurveyMonsterService.Question) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/CreateSurvey", ReplyAction:="http://tempuri.org/ISurveyWCFService/CreateSurveyResponse")>  _
        Function CreateSurvey(ByVal S As SurveyMonsterService.Survey) As SurveyMonsterService.Survey
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/CreateSurvey", ReplyAction:="http://tempuri.org/ISurveyWCFService/CreateSurveyResponse")>  _
        Function CreateSurveyAsync(ByVal S As SurveyMonsterService.Survey) As System.Threading.Tasks.Task(Of SurveyMonsterService.Survey)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/SaveTranscript", ReplyAction:="http://tempuri.org/ISurveyWCFService/SaveTranscriptResponse")>  _
        Function SaveTranscript(ByVal NewTranscript As SurveyMonsterService.Transcript) As SurveyMonsterService.Transcript
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/SaveTranscript", ReplyAction:="http://tempuri.org/ISurveyWCFService/SaveTranscriptResponse")>  _
        Function SaveTranscriptAsync(ByVal NewTranscript As SurveyMonsterService.Transcript) As System.Threading.Tasks.Task(Of SurveyMonsterService.Transcript)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/GetQuestionAnswer", ReplyAction:="http://tempuri.org/ISurveyWCFService/GetQuestionAnswerResponse")>  _
        Function GetQuestionAnswer(ByVal QuestionId As Integer) As SurveyMonsterService.PossibleAnswer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/GetQuestionAnswer", ReplyAction:="http://tempuri.org/ISurveyWCFService/GetQuestionAnswerResponse")>  _
        Function GetQuestionAnswerAsync(ByVal QuestionId As Integer) As System.Threading.Tasks.Task(Of SurveyMonsterService.PossibleAnswer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/GetQuestionPossibleAnswers", ReplyAction:="http://tempuri.org/ISurveyWCFService/GetQuestionPossibleAnswersResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.CompositeType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.Survey())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.Survey)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.Question())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.Question)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.PossibleAnswer())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.PossibleAnswer)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.TranscriptItem())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.TranscriptItem)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.Transcript)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.Transcript()))>  _
        Function GetQuestionPossibleAnswers(ByVal QuestionId As Integer) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/GetQuestionPossibleAnswers", ReplyAction:="http://tempuri.org/ISurveyWCFService/GetQuestionPossibleAnswersResponse")>  _
        Function GetQuestionPossibleAnswersAsync(ByVal QuestionId As Integer) As System.Threading.Tasks.Task(Of Object)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/GetSurveyQuestions", ReplyAction:="http://tempuri.org/ISurveyWCFService/GetSurveyQuestionsResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.CompositeType)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.Survey())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.Survey)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.Question())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.Question)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.PossibleAnswer())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.PossibleAnswer)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.TranscriptItem())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.TranscriptItem)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.Transcript)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SurveyMonsterService.Transcript()))>  _
        Function GetSurveyQuestions(ByVal SurveyId As Integer) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/GetSurveyQuestions", ReplyAction:="http://tempuri.org/ISurveyWCFService/GetSurveyQuestionsResponse")>  _
        Function GetSurveyQuestionsAsync(ByVal SurveyId As Integer) As System.Threading.Tasks.Task(Of Object)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/GetSurvey", ReplyAction:="http://tempuri.org/ISurveyWCFService/GetSurveyResponse")>  _
        Function GetSurvey(ByVal SurveyId As Integer) As SurveyMonsterService.Survey
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/GetSurvey", ReplyAction:="http://tempuri.org/ISurveyWCFService/GetSurveyResponse")>  _
        Function GetSurveyAsync(ByVal SurveyId As Integer) As System.Threading.Tasks.Task(Of SurveyMonsterService.Survey)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/GetAllSurveys", ReplyAction:="http://tempuri.org/ISurveyWCFService/GetAllSurveysResponse")>  _
        Function GetAllSurveys() As SurveyMonsterService.Survey()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISurveyWCFService/GetAllSurveys", ReplyAction:="http://tempuri.org/ISurveyWCFService/GetAllSurveysResponse")>  _
        Function GetAllSurveysAsync() As System.Threading.Tasks.Task(Of SurveyMonsterService.Survey())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISurveyWCFServiceChannel
        Inherits SurveyMonsterService.ISurveyWCFService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SurveyWCFServiceClient
        Inherits System.ServiceModel.ClientBase(Of SurveyMonsterService.ISurveyWCFService)
        Implements SurveyMonsterService.ISurveyWCFService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetData(ByVal value As Integer) As String Implements SurveyMonsterService.ISurveyWCFService.GetData
            Return MyBase.Channel.GetData(value)
        End Function
        
        Public Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String) Implements SurveyMonsterService.ISurveyWCFService.GetDataAsync
            Return MyBase.Channel.GetDataAsync(value)
        End Function
        
        Public Function GetDataUsingDataContract(ByVal composite As SurveyMonsterService.CompositeType) As SurveyMonsterService.CompositeType Implements SurveyMonsterService.ISurveyWCFService.GetDataUsingDataContract
            Return MyBase.Channel.GetDataUsingDataContract(composite)
        End Function
        
        Public Function GetDataUsingDataContractAsync(ByVal composite As SurveyMonsterService.CompositeType) As System.Threading.Tasks.Task(Of SurveyMonsterService.CompositeType) Implements SurveyMonsterService.ISurveyWCFService.GetDataUsingDataContractAsync
            Return MyBase.Channel.GetDataUsingDataContractAsync(composite)
        End Function
        
        Public Function GetAllActiveSurveys() As SurveyMonsterService.Survey() Implements SurveyMonsterService.ISurveyWCFService.GetAllActiveSurveys
            Return MyBase.Channel.GetAllActiveSurveys
        End Function
        
        Public Function GetAllActiveSurveysAsync() As System.Threading.Tasks.Task(Of SurveyMonsterService.Survey()) Implements SurveyMonsterService.ISurveyWCFService.GetAllActiveSurveysAsync
            Return MyBase.Channel.GetAllActiveSurveysAsync
        End Function
        
        Public Function AddQuestion(ByVal SurveyId As Integer, ByVal Q As SurveyMonsterService.Question) As Boolean Implements SurveyMonsterService.ISurveyWCFService.AddQuestion
            Return MyBase.Channel.AddQuestion(SurveyId, Q)
        End Function
        
        Public Function AddQuestionAsync(ByVal SurveyId As Integer, ByVal Q As SurveyMonsterService.Question) As System.Threading.Tasks.Task(Of Boolean) Implements SurveyMonsterService.ISurveyWCFService.AddQuestionAsync
            Return MyBase.Channel.AddQuestionAsync(SurveyId, Q)
        End Function
        
        Public Function CreateSurvey(ByVal S As SurveyMonsterService.Survey) As SurveyMonsterService.Survey Implements SurveyMonsterService.ISurveyWCFService.CreateSurvey
            Return MyBase.Channel.CreateSurvey(S)
        End Function
        
        Public Function CreateSurveyAsync(ByVal S As SurveyMonsterService.Survey) As System.Threading.Tasks.Task(Of SurveyMonsterService.Survey) Implements SurveyMonsterService.ISurveyWCFService.CreateSurveyAsync
            Return MyBase.Channel.CreateSurveyAsync(S)
        End Function
        
        Public Function SaveTranscript(ByVal NewTranscript As SurveyMonsterService.Transcript) As SurveyMonsterService.Transcript Implements SurveyMonsterService.ISurveyWCFService.SaveTranscript
            Return MyBase.Channel.SaveTranscript(NewTranscript)
        End Function
        
        Public Function SaveTranscriptAsync(ByVal NewTranscript As SurveyMonsterService.Transcript) As System.Threading.Tasks.Task(Of SurveyMonsterService.Transcript) Implements SurveyMonsterService.ISurveyWCFService.SaveTranscriptAsync
            Return MyBase.Channel.SaveTranscriptAsync(NewTranscript)
        End Function
        
        Public Function GetQuestionAnswer(ByVal QuestionId As Integer) As SurveyMonsterService.PossibleAnswer Implements SurveyMonsterService.ISurveyWCFService.GetQuestionAnswer
            Return MyBase.Channel.GetQuestionAnswer(QuestionId)
        End Function
        
        Public Function GetQuestionAnswerAsync(ByVal QuestionId As Integer) As System.Threading.Tasks.Task(Of SurveyMonsterService.PossibleAnswer) Implements SurveyMonsterService.ISurveyWCFService.GetQuestionAnswerAsync
            Return MyBase.Channel.GetQuestionAnswerAsync(QuestionId)
        End Function
        
        Public Function GetQuestionPossibleAnswers(ByVal QuestionId As Integer) As Object Implements SurveyMonsterService.ISurveyWCFService.GetQuestionPossibleAnswers
            Return MyBase.Channel.GetQuestionPossibleAnswers(QuestionId)
        End Function
        
        Public Function GetQuestionPossibleAnswersAsync(ByVal QuestionId As Integer) As System.Threading.Tasks.Task(Of Object) Implements SurveyMonsterService.ISurveyWCFService.GetQuestionPossibleAnswersAsync
            Return MyBase.Channel.GetQuestionPossibleAnswersAsync(QuestionId)
        End Function
        
        Public Function GetSurveyQuestions(ByVal SurveyId As Integer) As Object Implements SurveyMonsterService.ISurveyWCFService.GetSurveyQuestions
            Return MyBase.Channel.GetSurveyQuestions(SurveyId)
        End Function
        
        Public Function GetSurveyQuestionsAsync(ByVal SurveyId As Integer) As System.Threading.Tasks.Task(Of Object) Implements SurveyMonsterService.ISurveyWCFService.GetSurveyQuestionsAsync
            Return MyBase.Channel.GetSurveyQuestionsAsync(SurveyId)
        End Function
        
        Public Function GetSurvey(ByVal SurveyId As Integer) As SurveyMonsterService.Survey Implements SurveyMonsterService.ISurveyWCFService.GetSurvey
            Return MyBase.Channel.GetSurvey(SurveyId)
        End Function
        
        Public Function GetSurveyAsync(ByVal SurveyId As Integer) As System.Threading.Tasks.Task(Of SurveyMonsterService.Survey) Implements SurveyMonsterService.ISurveyWCFService.GetSurveyAsync
            Return MyBase.Channel.GetSurveyAsync(SurveyId)
        End Function
        
        Public Function GetAllSurveys() As SurveyMonsterService.Survey() Implements SurveyMonsterService.ISurveyWCFService.GetAllSurveys
            Return MyBase.Channel.GetAllSurveys
        End Function
        
        Public Function GetAllSurveysAsync() As System.Threading.Tasks.Task(Of SurveyMonsterService.Survey()) Implements SurveyMonsterService.ISurveyWCFService.GetAllSurveysAsync
            Return MyBase.Channel.GetAllSurveysAsync
        End Function
    End Class
End Namespace
