'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace SurveyWCF

    Partial Public Class Survey
        Public Property Id As Integer
        Public Property SurveyTitle As String
        Public Property Description As String
        Public Property DateCreated As Date
        Public Property CreatedBy As String
        Public Property LastModified As Nullable(Of Date)
        Public Property LastModifiedBy As String
        Public Property StartDate As Nullable(Of Date)
        Public Property EndDate As Nullable(Of Date)
        Public Property IsActive As Nullable(Of Boolean)
    
        Public Overridable Property Questions As ICollection(Of Question) = New HashSet(Of Question)
        Public Overridable Property Transcripts As ICollection(Of Transcript) = New HashSet(Of Transcript)
    
    End Class

End Namespace
