'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace SurveyWCF

    Partial Public Class SurveyMonsterEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=SurveyMonsterEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property PossibleAnswers() As DbSet(Of PossibleAnswer)
        Public Overridable Property Questions() As DbSet(Of Question)
        Public Overridable Property Surveys() As DbSet(Of Survey)
        Public Overridable Property Transcripts() As DbSet(Of Transcript)
        Public Overridable Property TranscriptItems() As DbSet(Of TranscriptItem)
    
    End Class

End Namespace
