'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace SurveyWCF

    Partial Public Class TranscriptItem
        Public Property Id As Integer
        Public Property TranscriptId As Integer
        Public Property QuestionId As Integer
        Public Property IsCorrect As Boolean
        Public Property SelectedAnswerId As Integer
        Public Property CreatedBy As String
        Public Property DateCreated As Date
        Public Property LastModified As Nullable(Of Date)
        Public Property ModifiedBy As String
    
        Public Overridable Property Transcript As Transcript
        Public Overridable Property Question As Question
    
    End Class

End Namespace
