'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace SurveyWCF

    Partial Public Class Transcript
        Public Property Id As Integer
        Public Property RespondentId As String
        Public Property DateCreated As Date
        Public Property CreatedBy As String
        Public Property LastModified As Nullable(Of Date)
        Public Property ModifiedBy As String
        Public Property QuestionId As Integer
        Public Property IsCorrect As Boolean
        Public Property SurveyId As Integer
        Public Property Score As Nullable(Of Decimal)
    
        Public Overridable Property Survey As Survey
        Public Overridable Property TranscriptItems As ICollection(Of TranscriptItem) = New HashSet(Of TranscriptItem)
    
    End Class

End Namespace
